analysis:
  cytb-xs:
    dataset: https://next.nextstrain.org/groups/trajectories/cytb-xs
    gene: nuc
    trim_begin: 1
    trim_end: 1140
    seq_length: 1140
  n450-xs:
    dataset: https://next.nextstrain.org/groups/trajectories/n450-xs
    gene: nuc
    seq_length: 450
  spike-xs:
    dataset: https://next.nextstrain.org/groups/trajectories/spike-xs
    gene: nuc
    trim_begin: 21563
    trim_end: 23617
    seq_length: 2055 # spike s1
  spike-sm:
    dataset: https://next.nextstrain.org/groups/trajectories/spike-sm
    gene: nuc
    trim_begin: 21563
    trim_end: 23617
    seq_length: 2055 # spike s1
  rdrp-paramyxoviridae:
    dataset: https://next.nextstrain.org/groups/trajectories-private/rdrp-paramyxoviridae
    gene: nuc
    seq_length: 1653
  rdrp-flaviviridae:
    dataset: https://next.nextstrain.org/groups/trajectories-private/rdrp-flaviviridae
    gene: nuc
    seq_length: 1884
  rdrp-picornaviridae:
    dataset: https://next.nextstrain.org/groups/trajectories-private/rdrp-picornaviridae
    gene: nuc
    seq_length: 1386
  # Subtrees auto-discovered from ../rdrp/phylogenetic/auspice/*/subtrees/
